using DecorationProjectScheduler.App.Helpers;
using DecorationProjectScheduler.App.Models;
using Npgsql;

namespace DecorationProjectScheduler.Api;

public sealed class PostgresSchedulerRepository
{
    private readonly string _connectionString;

    public PostgresSchedulerRepository(IConfiguration configuration)
    {
        _connectionString = configuration.GetConnectionString("Scheduler")
            ?? Environment.GetEnvironmentVariable("SCHEDULER_CONNECTION_STRING")
            ?? throw new InvalidOperationException("缺少数据库连接字符串 Scheduler。");
    }

    public async Task InitializeAsync()
    {
        await using var connection = new NpgsqlConnection(_connectionString);
        await connection.OpenAsync();

        await ExecuteAsync(connection, """
            CREATE TABLE IF NOT EXISTS employees (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name TEXT NOT NULL,
                role TEXT NOT NULL DEFAULT '',
                department TEXT NOT NULL DEFAULT ''
            );

            CREATE TABLE IF NOT EXISTS projects (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                project_code TEXT NOT NULL UNIQUE,
                name TEXT NOT NULL,
                status TEXT NOT NULL,
                manager_id INTEGER NOT NULL,
                area TEXT NOT NULL DEFAULT '',
                project_type TEXT NOT NULL DEFAULT '',
                operator_names TEXT NOT NULL DEFAULT '',
                task_plan TEXT NOT NULL DEFAULT '',
                start_date DATE NOT NULL,
                end_date DATE NOT NULL,
                summary TEXT NOT NULL DEFAULT '',
                updated_at TIMESTAMP NOT NULL,
                archived BOOLEAN NOT NULL DEFAULT FALSE
            );

            CREATE TABLE IF NOT EXISTS project_stages (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
                stage_name TEXT NOT NULL,
                sequence_no INTEGER NOT NULL,
                planned_date DATE NOT NULL,
                completed_date DATE NULL,
                status TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS tasks (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
                name TEXT NOT NULL,
                owner_id INTEGER NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
                workload_percent INTEGER NOT NULL,
                progress_percent INTEGER NOT NULL,
                start_date DATE NOT NULL,
                end_date DATE NOT NULL,
                status TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS site_visits (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
                visit_date DATE NOT NULL,
                issues TEXT NOT NULL,
                suggestions TEXT NOT NULL,
                photo_path TEXT NOT NULL DEFAULT '',
                rectification_status TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS handover_records (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
                handover_date DATE NOT NULL,
                participants TEXT NOT NULL,
                attachment_path TEXT NOT NULL DEFAULT '',
                notes TEXT NOT NULL DEFAULT ''
            );

            CREATE TABLE IF NOT EXISTS acceptance_records (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
                acceptance_date DATE NOT NULL,
                result TEXT NOT NULL,
                rectification_items TEXT NOT NULL,
                review_record TEXT NOT NULL,
                status TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS project_files (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
                category TEXT NOT NULL,
                file_name TEXT NOT NULL,
                file_path TEXT NOT NULL,
                uploaded_at TIMESTAMP NOT NULL
            );

            CREATE TABLE IF NOT EXISTS project_follow_ups (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
                task_id INTEGER NULL,
                content TEXT NOT NULL,
                operator_name TEXT NOT NULL,
                completed_at TIMESTAMP NOT NULL
            );
            """);
        // 正式版只初始化表结构，不自动写入演示员工，避免更新或迁移时污染公司人员数据。
    }

    public async Task<WorkspaceSnapshot> GetSnapshotAsync()
    {
        await using var connection = new NpgsqlConnection(_connectionString);
        await connection.OpenAsync();

        return new WorkspaceSnapshot
        {
            Employees = await ReadEmployeesAsync(connection),
            Projects = await ReadProjectsAsync(connection),
            ProjectStages = await ReadStagesAsync(connection),
            Tasks = await ReadTasksAsync(connection),
            SiteVisits = await ReadSiteVisitsAsync(connection),
            HandoverRecords = await ReadHandoversAsync(connection),
            AcceptanceRecords = await ReadAcceptancesAsync(connection),
            ProjectFiles = await ReadFilesAsync(connection),
            ProjectFollowUps = await ReadFollowUpsAsync(connection)
        };
    }

    public async Task AddEmployeeAsync(AddEmployeeRequest request)
    {
        await ExecuteAsync("""
            INSERT INTO employees (name, role, department)
            VALUES (@name, @role, @department);
            """,
            ("name", request.Name),
            ("role", request.Role),
            ("department", request.Department));
    }

    public async Task DeleteEmployeeAsync(int employeeId)
    {
        await ExecuteAsync("""
            DELETE FROM tasks WHERE owner_id = @employeeId;
            DELETE FROM employees WHERE id = @employeeId;
            """,
            ("employeeId", employeeId));
    }

    public async Task CreateProjectAsync(CreateProjectRequest request)
    {
        await using var connection = new NpgsqlConnection(_connectionString);
        await connection.OpenAsync();
        await using var transaction = await connection.BeginTransactionAsync();

        var code = $"{DateTime.Today:yyyy}{await ScalarAsync<long>(connection, "SELECT COUNT(*) + 1 FROM projects;", transaction):000}";
        var projectId = await ScalarAsync<int>(connection, """
            INSERT INTO projects (project_code, name, status, manager_id, area, project_type, operator_names, task_plan, start_date, end_date, summary, updated_at, archived)
            VALUES (@code, @name, '规划中', @managerId, @area, @projectType, '', '', @startDate, @endDate, @summary, @updatedAt, FALSE)
            RETURNING id;
            """,
            transaction,
            ("code", code),
            ("name", request.Name),
            ("managerId", request.ManagerId),
            ("area", request.Area),
            ("projectType", request.ProjectType),
            ("startDate", request.StartDate.Date),
            ("endDate", request.EndDate.Date),
            ("summary", request.Summary),
            ("updatedAt", DateTime.Now));

        var totalDays = Math.Max((request.EndDate.Date - request.StartDate.Date).Days, DesignStageTemplates.DefaultStages.Length);
        for (var i = 0; i < DesignStageTemplates.DefaultStages.Length; i++)
        {
            await ExecuteAsync(connection, """
                INSERT INTO project_stages (project_id, stage_name, sequence_no, planned_date, completed_date, status)
                VALUES (@projectId, @stageName, @sequenceNo, @plannedDate, NULL, '待执行');
                """,
                transaction,
                ("projectId", projectId),
                ("stageName", DesignStageTemplates.DefaultStages[i]),
                ("sequenceNo", i + 1),
                ("plannedDate", request.StartDate.Date.AddDays(i * totalDays / DesignStageTemplates.DefaultStages.Length)));
        }

        await transaction.CommitAsync();
    }

    public async Task UpdateProjectAsync(int projectId, UpdateProjectRequest request)
    {
        await ExecuteAsync("""
            UPDATE projects
            SET name = @name,
                area = @area,
                project_type = @projectType,
                operator_names = @operatorNames,
                summary = @summary,
                task_plan = @taskPlan,
                updated_at = @updatedAt
            WHERE id = @projectId;
            """,
            ("projectId", projectId),
            ("name", request.Name),
            ("area", request.Area),
            ("projectType", request.ProjectType),
            ("operatorNames", request.OperatorNames),
            ("summary", request.Summary),
            ("taskPlan", request.TaskPlan),
            ("updatedAt", DateTime.Now));
    }

    public async Task DeleteProjectAsync(int projectId) =>
        await ExecuteAsync("DELETE FROM projects WHERE id = @projectId;", ("projectId", projectId));

    public async Task AddTaskAsync(AddTaskRequest request)
    {
        await ExecuteAsync("""
            INSERT INTO tasks (project_id, name, owner_id, workload_percent, progress_percent, start_date, end_date, status)
            VALUES (@projectId, @name, @ownerId, @workload, @progress, @startDate, @endDate, @status);
            """,
            ("projectId", request.ProjectId),
            ("name", request.Name),
            ("ownerId", request.OwnerId),
            ("workload", request.WorkloadPercent),
            ("progress", request.ProgressPercent),
            ("startDate", request.StartDate.Date),
            ("endDate", request.EndDate.Date),
            ("status", request.Status));
        await TouchProjectAsync(request.ProjectId);
    }

    public async Task UpdateTaskAsync(int taskId, UpdateTaskRequest request)
    {
        var projectId = await GetTaskProjectIdAsync(taskId);
        await ExecuteAsync("UPDATE tasks SET name = @name WHERE id = @taskId;", ("taskId", taskId), ("name", request.Name));
        await TouchProjectAsync(projectId);
    }

    public async Task UpdateTaskScheduleAsync(int taskId, UpdateTaskScheduleRequest request)
    {
        var previousProjectId = await GetTaskProjectIdAsync(taskId);
        await ExecuteAsync("""
            UPDATE tasks
            SET project_id = @projectId,
                name = @name,
                end_date = @endDate,
                status = CASE WHEN progress_percent >= 100 THEN '已完成' ELSE status END
            WHERE id = @taskId;
            """,
            ("taskId", taskId),
            ("projectId", request.ProjectId),
            ("name", request.Name),
            ("endDate", request.EndDate.Date));
        await TouchProjectAsync(previousProjectId);
        await TouchProjectAsync(request.ProjectId);
    }

    public async Task DeleteTaskAsync(int taskId)
    {
        var projectId = await GetTaskProjectIdAsync(taskId);
        await ExecuteAsync("DELETE FROM tasks WHERE id = @taskId;", ("taskId", taskId));
        await TouchProjectAsync(projectId);
    }

    public async Task CompleteTaskWithFollowUpAsync(int taskId)
    {
        await using var connection = new NpgsqlConnection(_connectionString);
        await connection.OpenAsync();
        await using var transaction = await connection.BeginTransactionAsync();

        await using var query = CreateCommand(connection, """
            SELECT tasks.project_id, tasks.name, COALESCE(employees.name, '')
            FROM tasks
            LEFT JOIN employees ON employees.id = tasks.owner_id
            WHERE tasks.id = @taskId;
            """,
            transaction,
            ("taskId", taskId));
        await using var reader = await query.ExecuteReaderAsync();
        if (!await reader.ReadAsync())
        {
            return;
        }

        var projectId = reader.GetInt32(0);
        var taskName = reader.GetString(1);
        var operatorName = reader.GetString(2);
        await reader.DisposeAsync();

        await ExecuteAsync(connection, "UPDATE tasks SET progress_percent = 100, status = '已完成' WHERE id = @taskId;", transaction, ("taskId", taskId));
        await ExecuteAsync(connection, """
            INSERT INTO project_follow_ups (project_id, task_id, content, operator_name, completed_at)
            VALUES (@projectId, @taskId, @content, @operatorName, @completedAt);
            """,
            transaction,
            ("projectId", projectId),
            ("taskId", taskId),
            ("content", taskName),
            ("operatorName", operatorName),
            ("completedAt", DateTime.Now));
        await TouchProjectAsync(connection, transaction, projectId);
        await transaction.CommitAsync();
    }

    public async Task AddProjectFollowUpAsync(AddProjectFollowUpRequest request)
    {
        await ExecuteAsync("""
            INSERT INTO project_follow_ups (project_id, task_id, content, operator_name, completed_at)
            VALUES (@projectId, @taskId, @content, @operatorName, @completedAt);
            """,
            ("projectId", request.ProjectId),
            ("taskId", (object?)request.TaskId ?? DBNull.Value),
            ("content", request.Content),
            ("operatorName", request.OperatorName),
            ("completedAt", request.CompletedAt));
        await TouchProjectAsync(request.ProjectId);
    }

    public async Task DeleteProjectFollowUpAsync(int followUpId)
    {
        var projectId = await ScalarAsync<int?>("SELECT project_id FROM project_follow_ups WHERE id = @followUpId;", ("followUpId", followUpId));
        if (projectId is null)
        {
            return;
        }

        await ExecuteAsync("DELETE FROM project_follow_ups WHERE id = @followUpId;", ("followUpId", followUpId));
        await TouchProjectAsync(projectId.Value);
    }

    public async Task AddSiteVisitAsync(AddSiteVisitRequest request)
    {
        await ExecuteAsync("""
            INSERT INTO site_visits (project_id, visit_date, issues, suggestions, photo_path, rectification_status)
            VALUES (@projectId, @visitDate, @issues, @suggestions, @photoPath, @status);
            """,
            ("projectId", request.ProjectId),
            ("visitDate", request.VisitDate.Date),
            ("issues", request.Issues),
            ("suggestions", request.Suggestions),
            ("photoPath", request.PhotoPath),
            ("status", request.RectificationStatus));
        await TouchProjectAsync(request.ProjectId);
    }

    public async Task AddAcceptanceAsync(AddAcceptanceRequest request)
    {
        await ExecuteAsync("""
            INSERT INTO acceptance_records (project_id, acceptance_date, result, rectification_items, review_record, status)
            VALUES (@projectId, @acceptanceDate, @result, @items, @review, @status);
            """,
            ("projectId", request.ProjectId),
            ("acceptanceDate", request.AcceptanceDate.Date),
            ("result", request.Result),
            ("items", request.RectificationItems),
            ("review", request.ReviewRecord),
            ("status", request.Status));
        await TouchProjectAsync(request.ProjectId);
    }

    public async Task AddProjectFileAsync(AddProjectFileRequest request)
    {
        await ExecuteAsync("""
            INSERT INTO project_files (project_id, category, file_name, file_path, uploaded_at)
            VALUES (@projectId, @category, @fileName, @filePath, @uploadedAt);
            """,
            ("projectId", request.ProjectId),
            ("category", request.Category),
            ("fileName", request.FileName),
            ("filePath", request.FilePath),
            ("uploadedAt", DateTime.Now));
        await TouchProjectAsync(request.ProjectId);
    }

    public async Task ToggleStageAsync(int stageId, bool complete)
    {
        var projectId = await ScalarAsync<int>("SELECT project_id FROM project_stages WHERE id = @stageId;", ("stageId", stageId));
        await ExecuteAsync("""
            UPDATE project_stages
            SET completed_date = @completedDate,
                status = @status
            WHERE id = @stageId;
            """,
            ("stageId", stageId),
            ("completedDate", complete ? DateTime.Today : DBNull.Value),
            ("status", complete ? "已完成" : "待执行"));
        await TouchProjectAsync(projectId);
    }

    private async Task<int> GetTaskProjectIdAsync(int taskId) =>
        await ScalarAsync<int>("SELECT project_id FROM tasks WHERE id = @taskId;", ("taskId", taskId));

    private async Task TouchProjectAsync(int projectId) =>
        await ExecuteAsync("UPDATE projects SET updated_at = @updatedAt WHERE id = @projectId;", ("projectId", projectId), ("updatedAt", DateTime.Now));

    private static async Task TouchProjectAsync(NpgsqlConnection connection, NpgsqlTransaction transaction, int projectId) =>
        await ExecuteAsync(connection, "UPDATE projects SET updated_at = @updatedAt WHERE id = @projectId;", transaction, ("projectId", projectId), ("updatedAt", DateTime.Now));

    private async Task<List<Employee>> ReadEmployeesAsync(NpgsqlConnection connection)
    {
        await using var command = new NpgsqlCommand("SELECT id, name, role, department FROM employees ORDER BY id;", connection);
        await using var reader = await command.ExecuteReaderAsync();
        var list = new List<Employee>();
        while (await reader.ReadAsync())
        {
            list.Add(new Employee { Id = reader.GetInt32(0), Name = reader.GetString(1), Role = reader.GetString(2), Department = reader.GetString(3) });
        }

        return list;
    }

    private async Task<List<Project>> ReadProjectsAsync(NpgsqlConnection connection)
    {
        await using var command = new NpgsqlCommand("""
            SELECT id, project_code, name, status, manager_id, area, project_type, operator_names, task_plan, start_date, end_date, summary, updated_at, archived
            FROM projects
            ORDER BY updated_at DESC;
            """, connection);
        await using var reader = await command.ExecuteReaderAsync();
        var list = new List<Project>();
        while (await reader.ReadAsync())
        {
            list.Add(new Project
            {
                Id = reader.GetInt32(0),
                ProjectCode = reader.GetString(1),
                Name = reader.GetString(2),
                Status = reader.GetString(3),
                ManagerId = reader.GetInt32(4),
                Area = reader.GetString(5),
                ProjectType = reader.GetString(6),
                OperatorNames = reader.GetString(7),
                TaskPlan = reader.GetString(8),
                StartDate = reader.GetDateTime(9),
                EndDate = reader.GetDateTime(10),
                Summary = reader.GetString(11),
                UpdatedAt = reader.GetDateTime(12),
                Archived = reader.GetBoolean(13)
            });
        }

        return list;
    }

    private static async Task<List<ProjectStage>> ReadStagesAsync(NpgsqlConnection connection)
    {
        await using var command = new NpgsqlCommand("SELECT id, project_id, stage_name, sequence_no, planned_date, completed_date, status FROM project_stages ORDER BY project_id, sequence_no;", connection);
        await using var reader = await command.ExecuteReaderAsync();
        var list = new List<ProjectStage>();
        while (await reader.ReadAsync())
        {
            list.Add(new ProjectStage
            {
                Id = reader.GetInt32(0),
                ProjectId = reader.GetInt32(1),
                StageName = reader.GetString(2),
                SequenceNo = reader.GetInt32(3),
                PlannedDate = reader.GetDateTime(4),
                CompletedDate = reader.IsDBNull(5) ? null : reader.GetDateTime(5),
                Status = reader.GetString(6)
            });
        }

        return list;
    }

    private static async Task<List<WorkTask>> ReadTasksAsync(NpgsqlConnection connection)
    {
        await using var command = new NpgsqlCommand("SELECT id, project_id, name, owner_id, workload_percent, progress_percent, start_date, end_date, status FROM tasks ORDER BY end_date;", connection);
        await using var reader = await command.ExecuteReaderAsync();
        var list = new List<WorkTask>();
        while (await reader.ReadAsync())
        {
            list.Add(new WorkTask
            {
                Id = reader.GetInt32(0),
                ProjectId = reader.GetInt32(1),
                Name = reader.GetString(2),
                OwnerId = reader.GetInt32(3),
                WorkloadPercent = reader.GetInt32(4),
                ProgressPercent = reader.GetInt32(5),
                StartDate = reader.GetDateTime(6),
                EndDate = reader.GetDateTime(7),
                Status = reader.GetString(8)
            });
        }

        return list;
    }

    private static async Task<List<SiteVisit>> ReadSiteVisitsAsync(NpgsqlConnection connection)
    {
        await using var command = new NpgsqlCommand("SELECT id, project_id, visit_date, issues, suggestions, photo_path, rectification_status FROM site_visits ORDER BY visit_date DESC;", connection);
        await using var reader = await command.ExecuteReaderAsync();
        var list = new List<SiteVisit>();
        while (await reader.ReadAsync())
        {
            list.Add(new SiteVisit { Id = reader.GetInt32(0), ProjectId = reader.GetInt32(1), VisitDate = reader.GetDateTime(2), Issues = reader.GetString(3), Suggestions = reader.GetString(4), PhotoPath = reader.GetString(5), RectificationStatus = reader.GetString(6) });
        }

        return list;
    }

    private static async Task<List<HandoverRecord>> ReadHandoversAsync(NpgsqlConnection connection)
    {
        await using var command = new NpgsqlCommand("SELECT id, project_id, handover_date, participants, attachment_path, notes FROM handover_records ORDER BY handover_date DESC;", connection);
        await using var reader = await command.ExecuteReaderAsync();
        var list = new List<HandoverRecord>();
        while (await reader.ReadAsync())
        {
            list.Add(new HandoverRecord { Id = reader.GetInt32(0), ProjectId = reader.GetInt32(1), HandoverDate = reader.GetDateTime(2), Participants = reader.GetString(3), AttachmentPath = reader.GetString(4), Notes = reader.GetString(5) });
        }

        return list;
    }

    private static async Task<List<AcceptanceRecord>> ReadAcceptancesAsync(NpgsqlConnection connection)
    {
        await using var command = new NpgsqlCommand("SELECT id, project_id, acceptance_date, result, rectification_items, review_record, status FROM acceptance_records ORDER BY acceptance_date DESC;", connection);
        await using var reader = await command.ExecuteReaderAsync();
        var list = new List<AcceptanceRecord>();
        while (await reader.ReadAsync())
        {
            list.Add(new AcceptanceRecord { Id = reader.GetInt32(0), ProjectId = reader.GetInt32(1), AcceptanceDate = reader.GetDateTime(2), Result = reader.GetString(3), RectificationItems = reader.GetString(4), ReviewRecord = reader.GetString(5), Status = reader.GetString(6) });
        }

        return list;
    }

    private static async Task<List<ProjectFileRecord>> ReadFilesAsync(NpgsqlConnection connection)
    {
        await using var command = new NpgsqlCommand("SELECT id, project_id, category, file_name, file_path, uploaded_at FROM project_files ORDER BY uploaded_at DESC;", connection);
        await using var reader = await command.ExecuteReaderAsync();
        var list = new List<ProjectFileRecord>();
        while (await reader.ReadAsync())
        {
            list.Add(new ProjectFileRecord { Id = reader.GetInt32(0), ProjectId = reader.GetInt32(1), Category = reader.GetString(2), FileName = reader.GetString(3), FilePath = reader.GetString(4), UploadedAt = reader.GetDateTime(5) });
        }

        return list;
    }

    private static async Task<List<ProjectFollowUp>> ReadFollowUpsAsync(NpgsqlConnection connection)
    {
        await using var command = new NpgsqlCommand("SELECT id, project_id, task_id, content, operator_name, completed_at FROM project_follow_ups ORDER BY completed_at DESC;", connection);
        await using var reader = await command.ExecuteReaderAsync();
        var list = new List<ProjectFollowUp>();
        while (await reader.ReadAsync())
        {
            list.Add(new ProjectFollowUp
            {
                Id = reader.GetInt32(0),
                ProjectId = reader.GetInt32(1),
                TaskId = reader.IsDBNull(2) ? null : reader.GetInt32(2),
                Content = reader.GetString(3),
                OperatorName = reader.GetString(4),
                CompletedAt = reader.GetDateTime(5)
            });
        }

        return list;
    }

    private async Task ExecuteAsync(string sql, params (string Name, object? Value)[] parameters)
    {
        await using var connection = new NpgsqlConnection(_connectionString);
        await connection.OpenAsync();
        await ExecuteAsync(connection, sql, null, parameters);
    }

    private static async Task ExecuteAsync(NpgsqlConnection connection, string sql, NpgsqlTransaction? transaction = null, params (string Name, object? Value)[] parameters)
    {
        await using var command = CreateCommand(connection, sql, transaction, parameters);
        await command.ExecuteNonQueryAsync();
    }

    private async Task<T> ScalarAsync<T>(string sql, params (string Name, object? Value)[] parameters)
    {
        await using var connection = new NpgsqlConnection(_connectionString);
        await connection.OpenAsync();
        return await ScalarAsync<T>(connection, sql, null, parameters);
    }

    private static async Task<T> ScalarAsync<T>(NpgsqlConnection connection, string sql, NpgsqlTransaction? transaction = null, params (string Name, object? Value)[] parameters)
    {
        await using var command = CreateCommand(connection, sql, transaction, parameters);
        var value = await command.ExecuteScalarAsync();
        if (value is null or DBNull)
        {
            return default!;
        }

        return (T)Convert.ChangeType(value, Nullable.GetUnderlyingType(typeof(T)) ?? typeof(T));
    }

    private static NpgsqlCommand CreateCommand(NpgsqlConnection connection, string sql, NpgsqlTransaction? transaction = null, params (string Name, object? Value)[] parameters)
    {
        var command = new NpgsqlCommand(sql, connection, transaction);
        foreach (var (name, value) in parameters)
        {
            command.Parameters.AddWithValue(name, value ?? DBNull.Value);
        }

        return command;
    }
}
